### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by sannchhiitttt** [PixelExperience/manifest#15]
Building Rom for violet.

ubuntu@ip-172-31-42-214:~/android/pe$ lunch aosp_violet-userdebug
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for
 product "aosp_violet".
07:56:53 dumpvars failed with: exit status 1
Device violet not found. Attempting to retrieve device repository from PixelExpe
rience-Devices Github (http://github.com/PixelExperience-Devices).
Found repository: device_xiaomi_violet
Checking branch info
Calculated revision: eleven
Adding dependency:
Repository: device_xiaomi_violet
Branch: eleven
Remote: pixel-devices
Path: device/xiaomi/violet

.................

*mka bacon -j$(nproc --all)*

FAILED:                                                          
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd (EX
ECUTABLES android-arm) missing lib_driver_cmd_simulated (STATIC_L
IBRARIES android-arm)"                                           
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment i
f this is intentional, but that may defer real problems until lat
er in the build.                                                 
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd_noh
idl (EXECUTABLES android-arm) missing lib_driver_cmd_simulated (S
TATIC_LIBRARIES android-arm)"                                    
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment i
f this is intentional, but that may defer real problems until lat
er in the build.                                                 
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: "wpa_

[ 99% 24812/24813] finishing build rules ...                     
FAILED:                                                          
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd (EX
ECUTABLES android-arm) missing lib_driver_cmd_simulated (STATIC_L
IBRARIES android-arm)"                                           
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment i
f this is intentional, but that may defer real problems until lat
er in the build.                                                 
external/wpa_supplicant_8/hostapd/Android.mk: error: "hostapd_noh
idl (EXECUTABLES android-arm) missing lib_driver_cmd_simulated (S
TATIC_LIBRARIES android-arm)"                                    
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment i
f this is intentional, but that may defer real problems until lat
er in the build.                                                 
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: "wpa_
supplicant (EXECUTABLES android-arm) missing lib_driver_cmd_simul
ated (STATIC_LIBRARIES android-arm)"                             
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment i
f this is intentional, but that may defer real problems until lat
er in the build.                                                 
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: "libwifi-h
al (SHARED_LIBRARIES android-arm) missing libwifi-hal-emu (STATIC
_LIBRARIES android-arm)"                                         
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment i
f this is intentional, but that may defer real problems until lat
er in the build.                                                 
packages/apps/Camera2/Android.mk: warning: "Camera2 (app:sdk) sho
uld not link against libjni_tinyplanet (native:platform)"        
packages/apps/Camera2/Android.mk: warning: "Camera2 (app:sdk) sho
uld not link against libjni_jpegutil (native:platform)"          
build/make/core/main.mk:950: error: exiting from previous errors.
08:08:51 ckati failed with: exit status 1                        
                                                                 
#### failed to build some targets (41 seconds) ####              
                                                                 
ubuntu@ip-172-31-42-214:~/android/pe$

**Comment by Hasaber8** [comment]
@AndroidBuildersHelp

**Comment by Maitreya29** [comment]
bruh wot

**Comment by sannchhiitttt** [comment]
> @AndroidBuildersHelp on telegram

Ok thanks broh
